main: com.windinn.windcore.WindCore
name: WindCore
version: 0.2
api-version: 1.15
author: Windinn
description: The must-have for all servers!
commands:
  
  clearchat:
    description: Clear the chat.
    permission: windcore.clearchat
    aliases: cchat

  feed:
    description: Feed yourself or a player.
    permission: windcore.feed

  heal:
    description: Heal yourself or a player.
    permission: windcore.heal

  nickname:
    description: Change your nickname.
    permission: windcore.nickname
    aliases: nick
