main: com.windinn.windcore.WindCore
name: WindCore
version: BETA-0.6
api-version: 1.15
author: Windinn
description: The must-have for all servers!
commands:
  
  clearchat:
    description: Clear the chat.
    permission: windcore.clearchat
    aliases: cchat

  discord:
    description: Check the server discord.
    permission: windcore.discord
    aliases: [disc]

  feed:
    description: Feed yourself or a player.
    permission: windcore.feed

  fly:
    description: Toggle flight mode.
    permission: windcore.fly

  heal:
    description: Heal yourself or a player.
    permission: windcore.heal

  inventorysee:
    description: Check the inventory of a player.
    permission: windcore.invsee
    aliases: invsee

  msg:
    description: Send a private message to a player.
    permission: windcore.msg
    aliases: [w, whisper, tell]

  nickname:
    description: Change your nickname.
    permission: windcore.nickname
    aliases: nick

  reply:
    description: Reply to your latest message.
    permission: windcore.reply
    aliases: [r]

  twitter:
    description: Check the Twitter of the server.
    permission: windcore.twitter
    aliases: [tweet]

  website:
    description: Check the website of the server.
    permissiond: windcore.website
    aliases: [web, site, internet, url]

  youtube:
    description: Check the YouTube channel of the server.
    permission: windcore.youtube
    aliases: [yt]